version: '3.5'

services:
  ant-design-pro_dev:
    ports:
      - 8005:8005
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: 'ant-design-pro_dev'
    command:
      - sh
      - -c
      - |
        yarn install
        npm run start
    volumes:
      - ../src:/usr/src/app/src
      - ../config:/usr/src/app/config
      - ../mock:/usr/src/app/mock
      - ../package.json:/usr/src/app/package.json
      - ../docker:/usr/src/app/docker

